# Generated by Django 4.2.1 on 2023-05-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name_plural": "entries"},
        ),
    ]
